apiVersion: apps/v1
kind: Deployment
metadata:
  name:  redmine
  labels:
    app:  redmine
spec:
  selector:
    matchLabels:
      app: redmine
  replicas: 1
  template:
    metadata:
      labels:
        app:  redmine
    spec:
      containers:
      - name:  redmine
        image: redmine:latest # Image name from docker hub 
        ports: 
        - containerPort: 3000
        env:
          - name: "REDMINE_DB_MYSQL"
            value: "redmine-mysql" # Must be the mysql service name
          - name: "REDMINE_DB_PASSWORD"
            value: "mysecretpassword"