apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikijs-mysql-pv-claim
  labels:
    app: wikijs-mysql
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# Word pas aangemaakt wanneer een pod die effectief wilt gebruiken, anders bestaat die nog niet